version: '3'
services:
    minio:
        build:
            context: ./
            dockerfile: ./images/minio/Dockerfile
        container_name: minio
        restart: always
        volumes:
            - ./data:/home/pi/data
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        command: minio server --address :9000 --console-address :9001 data/