FROM bde2020/spark-master:3.1.1-hadoop3.2

RUN curl -s https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.0/hadoop-aws-3.2.0.jar -o /spark/jars/hadoop-aws-3.2.0.jar \
&& curl -s https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.980/aws-java-sdk-bundle-1.11.980.jar -o /spark/jars/aws-java-sdk-bundle-1.11.980.jar 
